### ISSUE TITLE
add --help flag to CLI to explain usage

### ISSUE THREAD

**Issue by willem-delbare** [officient/readable#13]
eg --help could explain how to save a new baseline,..

**Comment by denys-potapov** [comment]
Done. I use console colors, it pretty neat in linux. Can some one test if nothing broken in windows?

![Знімок екрану з 2020-05-08 14-35-28](https://user-images.githubusercontent.com/2123712/81401991-32d1e000-9139-11ea-90ba-dd8a191ced3b.png)
