### ISSUE TITLE
Fix file-max-size undefined line & column

### ISSUE THREAD

**Issue by SemProvoost** [officient/readable#14]
`tokens.current()`for file-max-size is `{ body: '', type: 9 }` here: https://github.com/officient/readable/blob/47980bf38cfa1252121791c5001b67bfe3f15159/src/rules/file-max-size.js#L25

making `    at line ${token.line} column ${token.column}` result in _at line *undefined* column *undefined*_.

Maybe just remove the line/column comment in case of file-max-size as it doesn't have a specific ln/col?

**Comment by SemProvoost** [comment]
![image](https://user-images.githubusercontent.com/27961543/83540216-4aae4100-a4f8-11ea-9a2a-fab7c2f897fe.png)

**Comment by Illyism** [comment]
Related https://github.com/officient/readable/issues/15

**Comment by denys-potapov** [comment]
FIxed in 9b63c02
