### ISSUE TITLE
Make output output paths with line and column included

### ISSUE THREAD

**Issue by Illyism** [officient/readable#15]
# Before

```
server/controllers/dashboard/employeeCount.php
  Class have no comment above.
    at line 4 column 5
```

# Proposal 

```
server/controllers/dashboard/employeeCount.php:4:5
  Class have no comment above.
```

This will allow VSCode to pick it up and open the file directly on the right position.

![image](https://user-images.githubusercontent.com/304283/83882416-5f7e1500-a742-11ea-8eda-c7a014c173b2.png)

**Comment by denys-potapov** [comment]
Fixed in f52261e
